name: Run Python Script

on:
  schedule:
    - cron: "0 10 * * *"   # 6 AM Eastern (EDT)
    - cron: "0 21 * * *"   # 5 PM Eastern (EDT)
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget xvfb
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          # remove conflicting system chromedriver
          sudo rm -f /usr/bin/chromedriver


      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          EMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # <-- add this
        run: |
          python DataPipeline/build_datasets_github.py
