name: Run Python Script

on:
  schedule:
    - cron: "0 6 * * *"   # 6 AM UTC
    - cron: "0 17 * * *"  # 5 PM UTC
  workflow_dispatch: 

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget xvfb
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          # remove conflicting system chromedriver
          sudo rm -f /usr/bin/chromedriver


      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          EMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        run: |
          python DataPipeline/build_datasets_github.py
